// Define your own mock data here:
export const standard = (/* vars, { ctx, req } */) => ({
  userByNickname: {
    __typename: 'User',
    links: [
      {
        __typename: 'Link',
        id: 'c1cd3093-305f-46c7-bbb2-987052436fdf',
        title:
          'leakage: browser-based timerless speculative execution attacks on apple dEvices',
        submittedBy: {
          __typename: 'User',
          lastName: 'Dutton',
          nickname: 'selfteachme',
          firstName: 'Amy',
        },
        link: 'https://google.com',
        countVotes: 1,
        countComments: 0,
        currentUserVote: null,
        createdAt: '2023-11-14T21:38:51.166Z',
        updatedAt: '2023-11-14T21:38:35.468Z',
        currentUserFavorite: false,
      },
      {
        __typename: 'Link',
        id: '1e8665a9-c845-480a-92d4-173825cc019b',
        title: 'Apple',
        submittedBy: {
          __typename: 'User',
          lastName: 'Dutton',
          nickname: 'selfteachme',
          firstName: 'Amy',
        },
        link: 'https://apple.com',
        countVotes: 1,
        countComments: 14,
        currentUserVote: null,
        createdAt: '2023-11-14T22:29:17.845Z',
        updatedAt: '2023-11-14T22:29:04.820Z',
        currentUserFavorite: false,
      },
      {
        __typename: 'Link',
        id: 'f986382c-d586-4bf2-8abf-ddd92a9bcbc4',
        title: 'Google',
        submittedBy: {
          __typename: 'User',
          lastName: 'Dutton',
          nickname: 'selfteachme',
          firstName: 'Amy',
        },
        link: 'https://google.com',
        countVotes: 0,
        countComments: 10,
        currentUserVote: null,
        createdAt: '2023-11-15T12:51:16.988Z',
        updatedAt: '2023-11-15T12:51:01.838Z',
        currentUserFavorite: false,
      },
      {
        __typename: 'Link',
        id: '6d96c5ca-3f2f-45d3-a7c3-bb1c307ca930',
        title: 'RedwoodJS',
        submittedBy: {
          __typename: 'User',
          lastName: 'Dutton',
          nickname: 'selfteachme',
          firstName: 'Amy',
        },
        link: 'https://redwoodjs.com',
        countVotes: 0,
        countComments: 0,
        currentUserVote: null,
        createdAt: '2023-11-16T03:18:41.735Z',
        updatedAt: '2023-11-16T03:18:41.735Z',
        currentUserFavorite: false,
      },
      {
        __typename: 'Link',
        id: 'ff221d9e-9f08-408a-8c5a-dd5c901313fd',
        title: 'RedwoodJS Docs',
        submittedBy: {
          __typename: 'User',
          lastName: 'Dutton',
          nickname: 'selfteachme',
          firstName: 'Amy',
        },
        link: 'https://redwoodjs.com/docs/introduction',
        countVotes: 0,
        countComments: 0,
        currentUserVote: null,
        createdAt: '2023-11-16T03:26:53.346Z',
        updatedAt: '2023-11-16T03:26:53.346Z',
        currentUserFavorite: false,
      },
    ],
  },
})
