// This file is generated by npm run build:icons

export type IconName =
	| "arrow"
	| "facebook"
	| "github"
	| "heart--empty"
	| "heart--filled"
	| "hide"
	| "linkedin"
	| "show"
	| "twitter"
	| "up"
	| "youtube";
